backend/config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :statements do
    member do
      patch :archive
    end
  end
  resources :cards, only: [:index, :new, :create, :edit, :update]
  resources :users, only: [:index, :new, :create, :edit, :update]
  devise_for :users, path: '',
                     path_names: { sign_up: 'sign_up' },
                     controllers: {
                        registrations: 'admin/registrations'
                     }
  
  resources :categories, only: [:index, :new, :create, :edit, :update]
  resources :companies, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api do
    namespace :baas do
      post 'webhooks', to: 'webhooks#create'
    end
  end

  root to: 'statements#index'
end

backend/app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  has_many :statements, dependent: :destroy
end

backend/app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: %i[ edit update ]
  before_action :set_users, only: %i[new edit]

  # GET /cards or /cards.json
  def index
    @cards = Card.joins(:user).where(users: { company_id: current_user.company_id })
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards or /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to cards_url, notice: I18n.t('cards.create.success') }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1 or /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to cards_url, notice: I18n.t('cards.update.success') }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_card
      @card = Card.find(params[:id])
    end

    def set_users
      @users = User.where(role: 'employee')
    end

    def card_params
      params.require(:card).permit(:last4, :user_id)
    end
end

backend/app/helpers/cards_helper.rb
module CardsHelper
  def user_select(form, users)
    users = users.where(company_id: current_user.company_id)
    form.collection_select(:user_id, users, :id, :name, prompt: 'Selecione um funcionário')
  end
end

backend/app/views/cards/_form.html.erb
<%= form_with(model: card, local: true) do |form| %>
  <% if card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :last4 %>
    <%= form.text_field :last4 %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= user_select(form, @users) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

backend/app/views/cards/edit.html.erb
<h1>Editing Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

backend/app/views/cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cards</h1>

<table>
  <thead>
    <tr>
      <th>Last4</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= card.last4 %></td>
        <td><%= card.user.name %></td>
        <td><%= link_to 'Edit', edit_card_path(card) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Card', new_card_path %>

backend/app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Back', cards_path %>